print('********* print these following lines **************')
print('this is \\\\ double backslash')
print('these are /\\/\\/\\/\\/\\ mountain')
print('he is \t awesome')
print('\\\" \\n \\t \\')
print('********* print these following lines **************')
print(r'this is \\ double backslash')
print(r'these are /\/\/\/\/\ mountain')
print('he is \t awesome')
